# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.10
_src_path: gh:epics-containers/deployment-template-argocd
argocd_project: esq51579
argocd_server: argocd.diamond.ac.uk
cluster_name: argus
cluster_namespace: esq51579
deployment_repo: https://github.com/marcelldls/bl01t-deployment
description: bl01t IOC Instances and Services
git_platform: github.com
github_org: marcelldls
ioc_group: bl01t
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
services_release: 2024.8.1
services_repo: https://github.com/marcelldls/bl01t-services
