apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bl01t
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: esq51579
  destination:
    name: argus
    namespace: esq51579
  source:
    path: apps
    repoURL: https://github.com/marcelldls/bl01t-deployment
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true